# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f503ff26d6e7e1cabcc3cd21c6faf59922e2e1e4cc391c61674e9973ab60829e2e4793afee5286f7ad845f36f3f4ce959f00aab849ef6b5a1d998d8af1d8d635

test:
  secret_key_base: 961812897d43664971c62b1614ac0da5568866d8da67abad9efe34e2b1dfcff104e54d959140e932b9ee3ff8610ab91c8be853d4e5f7e2d793f8ffeaec040583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
